pmb.parse: DeviceinfoSchema: remove broken @Cache
Using @Cache here causes "pmbootstrap install" to fail, for example with
v26.06:samsung-gt58:plasma-mobile as seen here:
https://builds.sr.ht/~postmarketos/job/1821267

Fix for:
  [15:50:37] Traceback (most recent call last):
    File "/home/build/pmbootstrap/pmb/__init__.py", line 113, in main
      run_command(args)
      ~~~~~~~~~~~^^^^^^
    File "/home/build/pmbootstrap/pmb/commands/__init__.py", line 139, in run_command
      install(
      ~~~~~~~^
          args.add,
          ^^^^^^^^^
      ...<27 lines>...
          args.zap,
          ^^^^^^^^^
      )
      ^
    File "/home/build/pmbootstrap/pmb/commands/install.py", line 113, in install
      pmb.install.install(
      ~~~~~~~~~~~~~~~~~~~^
          add,
          ^^^^
      ...<26 lines>...
          is_split,
          ^^^^^^^^^
      )
      ^
    File "/home/build/pmbootstrap/pmb/install/_install.py", line 1470, in install
      install_system_image(
      ~~~~~~~~~~~~~~~~~~~~^
          cipher,
          ^^^^^^^
      ...<14 lines>...
          disk=disk,
          ^^^^^^^^^^
      )
      ^
    File "/home/build/pmbootstrap/pmb/install/_install.py", line 899, in install_system_image
      pmb.install.partition(layout, size_boot)
      ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
    File "/home/build/pmbootstrap/pmb/install/partition.py", line 73, in partition
      or pmb.parse.deviceinfo_schema_default_boot_filesystem()
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
    File "/home/build/pmbootstrap/pmb/meta/__init__.py", line 41, in __call__
      self.cache.cache[key] = self.func(*args, **kwargs)
                              ~~~~~~~~~^^^^^^^^^^^^^^^^^
    File "/home/build/pmbootstrap/pmb/parse/deviceinfo.py", line 436, in deviceinfo_schema_default_boot_filesystem
      variable = deviceinfo_schema().get("flash", "boot_filesystem")
    File "/home/build/pmbootstrap/pmb/meta/__init__.py", line 33, in __call__
      key = self.cache.build_key(self.func, *args, **kwargs)
    File "/home/build/pmbootstrap/pmb/meta/__init__.py", line 101, in build_key
      raise ValueError(
      ...<2 lines>...
      )
  ValueError: Invalid cache key argument variable_name in function pmb.parse.deviceinfo.get

Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/merge_requests/2996>