pmb.helpers.lint: fix keyerror (MR 2397)
repo is a Path obj now, and its name is used as a key in the dest_paths dict.

Fixes this failure:

    working_dir=dest_paths[repo],
                ~~~~~~~~~~^^^^^^
KeyError: PosixPath('/home/clayton/src/pmaports')