setup.py: adjust path to pmb.__version__
setup.py is on its way out, but it isn't replaced just yet. Adjust the
code that finds the version.

I'm pushing this directly to master as this fix is trivial and unbreaks
packaging current master of pmbootstrap.

Fix for (from pmbootstrap AUR package):
$ pip install build wheel
$ python -m build --wheel --no-isolation
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    {"edge": "2.12.11-r0",
    ^
SyntaxError: '{' was never closed

Fixes: 1d067708 ("Move version to pmb.__version__")
Fixes: pmbootstrap#2226